# this is an example of the Uber API
# as a demonstration of an API spec in YAML
swagger: '2.0'
info:
  title: Blog Jonglage API
  description: Get to a better understanding of the juggling world
  version: "1.0.0"
# the domain of the service
host: localhost:5000
# array of all schemes that your API supports
schemes:
  - https
# will be prefixed to all paths
basePath: /
produces:
  - application/json
paths:
  /:
    get:
      summary: HTML of the website homepage
      tags:
        - Homepage
  /categories/{id}:
    get:
      summary: HTML for each category
      parameters:
        - name: id
          in: query
          description: Identifier of the category.
          required: true
          type: string
      tags:
        - Categories
      responses:
        200:
          description: An HTML for one Category
  /articles/{id}:
    get:
      summary: Send all the content of an article
      parameters:
        - name: id
          in: query
          description: Identifier of the article.
          required: true
          type: string
      tags:
        - Articles
  /articles/create:
    post:
      summary: Create one new article
      parameters:
        - name: name
        - name: author
        - name: description
        - name: content
        - name: category
        - name: tags
      tags:
        - Articles
  /articles/modify:
    post:
      summary: Modify one existing article
      tags:
        - Articles
  /articles/delete:
    post:
      summary: Delete one existinf article
      tags:
        - Articles
  /tags/create:
    post:
      summary: Create one new tag
      tags:
        - Tags
